version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:3.1-sdk
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: dotnet test src/tests/EntityGraphQL.Tests/