version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.0-sdk
    steps:
      - checkout
      - run:
          name: Base EQL tests
          command: dotnet test src/tests/EntityQueryLanguage.Tests/
      - run:
          name: GraphQL tests
          command: dotnet test src/tests/EntityQueryLanguage.GraphQL.Tests/